// packages/weather-app-react/src/components/home/hourlyWeather/HourlyWeatherToday.tsx
import { HourlyWeatherItem } from "./HourlyWeatherItem";
import type { BasicWeatherInfo, Timezone } from "../../../types";
import { calculateHour } from "../../../utils";

export const HourlyWeatherToday = ({
  weather,
  time
}: {
  weather: Partial<BasicWeatherInfo>[];
  time: Timezone;
}) => {
  return (
    <div className="hourly__weather">
      {weather.slice(1, 4).map((item, index) => {
        return (
          <HourlyWeatherItem
            key={item.dt}
            time={calculateHour(time.hour, index + 1)}
            temp={item!.temp!}
            icon={item!.weather![0].icon}
          />
        );
      })}
    </div>
  );
};

// packages/weather-app/src/components/home/hourlyWeather/HourlyWeatherToday.vue
<template>
  <div class="hourly__weather">
    <HourlyWeatherItem
      v-for="(item, index) in weather.slice(1, 4)"
      :key="item.dt"
      :time="calculateHour(time.hour, index + 1)"
      :temp="item.temp"
      :icon="item.weather[0].icon"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import type { BasicWeatherInfo, Timezone } from "@/types";
import HourlyWeatherItem from "./HourlyWeatherItem.vue";
import { calculateHour } from "@/utils";

export default defineComponent({
  components: {
    HourlyWeatherItem
  },
  props: {
    weather: {
      type: Array as () => Partial<BasicWeatherInfo>[],
      required: true
    },
    time: {
      type: Object as () => Timezone,
      required: true
    }
  },

  setup() {
    return { calculateHour };
  }
});
</script>

<style></style>
