// packages/weather-app-react/src/views/Daily.tsx
import { useContext, useState, useEffect, memo } from "react";
import { WeatherContext } from "../context/WeatherContext";
import { MainInfo } from "../components/daily/MainInfo";
import { HourlyWeather } from "../components/daily/HourlyWeather";
import { DaysList } from "../components/daily/DaysList";
import { getWeatherInfoAboutSelectedDay } from "../utils";

export const Daily = memo(() => {
  const { dailyWeather, currentSelectedDayIndex } = useContext(WeatherContext);

  const [
    { mainData, additionalData, temperature },
    setSelectedDayInfo
  ] = useState(
    getWeatherInfoAboutSelectedDay(currentSelectedDayIndex, dailyWeather!.daily)
  );

  useEffect(() => {
    setSelectedDayInfo(
      getWeatherInfoAboutSelectedDay(
        currentSelectedDayIndex,
        dailyWeather!.daily
      )
    );
  }, [currentSelectedDayIndex]);

  return (
    <div className="daily">
      <div className="daily__main">
        <MainInfo main={mainData} additional={additionalData} />
      </div>
      <div className="daily__additional">
        <HourlyWeather temp={temperature} />
        <DaysList weather={dailyWeather!.daily} />
      </div>
    </div>
  );
});

// packages/vue/src/views/Daily.vue
<template>
  <div class="daily">
    <div class="daily__main">
      <MainInfo
        :main="selectedDayWeatherInfo.mainData"
        :additional="selectedDayWeatherInfo.additionalData"
      />
    </div>
    <div class="daily__additional">
      <HourlyWeather :temp="selectedDayWeatherInfo.temperature" />
      <DaysList
        :weather="$store.state.dailyWeather.daily"
        :activeDayIndex="currentSelectedDayIndex"
        @change-active-day="currentSelectedDayIndex = $event"
      />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed, ref } from "vue";
import { getWeatherInfoAboutSelectedDay } from "@/utils";
import { useStore } from "vuex";
import MainInfo from "@/components/daily/MainInfo.vue";
import HourlyWeather from "@/components/daily/HourlyWeather.vue";
import DaysList from "@/components/daily/DaysList.vue";
export default defineComponent({
  components: {
    MainInfo,
    HourlyWeather,
    DaysList
  },
  setup() {
    const store = useStore();
    const currentSelectedDayIndex = ref(0);

    const selectedDayWeatherInfo = computed(() =>
      getWeatherInfoAboutSelectedDay(
        currentSelectedDayIndex.value,
        store.state.dailyWeather.daily
      )
    );

    return {
      currentSelectedDayIndex,
      selectedDayWeatherInfo
    };
  }
});
</script>

<style lang="scss" scoped>
@media all and (min-width: 1000px) {
  .daily {
    display: flex;
    justify-content: center;
    align-items: center;
    margin: 50px 0 40px 0;

    &__additional {
      width: 500px;
    }
  }
}
</style>
