// packages/weather-app/src/components/Main.vue
<template>
  <Loader v-if="$store.state.loading" />
  <div className="error__wrapper" v-else-if="$store.state.error">
    <Search @search="defaultSearch" @search-by-location="searchByLocation" />
    <Error />
  </div>
  <div v-else>
    <Search @search="defaultSearch" @search-by-location="searchByLocation" />
    <router-view></router-view>
    <Navbar />
  </div>
</template>

<script lang="ts">
import Navbar from "@/components/Navbar.vue";
import Error from "@/components/Error.vue";
import Loader from "@/components/Loader.vue";
import Search from "@/components/SearchControls.vue";

import { defineComponent } from "vue";
import { useStore } from "vuex";
import { getCityNameByCoordinates } from "@/utils";
export default defineComponent({
  components: {
    Navbar,
    Loader,
    Search,
    Error
  },
  setup() {
    const store = useStore();
    async function defaultSearch(query: string) {
      if (!query.trim().length) {
        store.dispatch("setError", true);
        return;
      }

      store.dispatch("setLoading", true);
      try {
        await store.dispatch("getCurrentWeather", query);

        const { coord } = store.state.currentWeather;
        await store.dispatch("getDailyWeather", {
          lat: coord.lat,
          lon: coord.lon
        });
        await store.dispatch("getTimezone", { lat: coord.lat, lon: coord.lon });

        store.dispatch("setError", false);
      } catch {
        store.dispatch("setError", true);
      } finally {
        store.dispatch("setLoading", false);
      }
    }

    //first search
    defaultSearch("London");

    async function searchByLocation() {
      store.dispatch("setLoading", true);

      if (!("geolocation" in navigator)) {
        store.dispatch("setError", true);
        return;
      }

      await navigator.geolocation.getCurrentPosition(
        async ({ coords }) => {
          const { address } = await getCityNameByCoordinates(coords);
          return await defaultSearch(address.city);
        },
        () => {
          store.dispatch("setLoading", false);
          store.dispatch("setError", true);
        }
      );
    }

    return { defaultSearch, searchByLocation };
  }
});
</script>

// packages/weather-app-react/src/components/Main.tsx
import { SearchControls } from "./SearchControls";
import { Home } from "../views/Home";
import { Daily } from "../views/Daily";
import { Loader } from "./Loader";
import { Navbar } from "./Navbar";
import { Error } from "./Error";
import { BrowserRouter as Router, Switch, Route } from "react-router-dom";

import { useContext, useEffect, memo } from "react";
import { WeatherContext } from "../context/WeatherContext";

import {
  getCurrentWeather,
  getDailyWeather,
  getTimezone,
  getCityNameByCoordinates
} from "../utils";

export const Main = memo(() => {
  const {
    error,
    loading,
    setLoading,
    setError,
    setCurrentWeather,
    setDailyWeather,
    setTimezone,
    setCurrentSelectedDayIndex
  } = useContext(WeatherContext);

  const search = async (city: string) => {
    if (!city.trim().length) {
      setError(true);
      return;
    }

    setLoading(true);
    try {
      const currentWeather = await getCurrentWeather(city);
      setCurrentWeather(currentWeather);

      const { coord } = currentWeather;
      setDailyWeather(await getDailyWeather(coord.lat, coord.lon));

      const { countryName, formatted } = await getTimezone(
        coord.lat,
        coord.lon
      );
      setTimezone({ countryName, hour: Number(formatted.substring(11, 13)) });

      setError(false);
      setCurrentSelectedDayIndex(0);
    } catch {
      setError(true);
    }
    setLoading(false);
  };

  const searchByLocation = async () => {
    setLoading(true);

    if (!("geolocation" in navigator)) {
      setError(true);
      return;
    }

    return navigator.geolocation.getCurrentPosition(
      async ({ coords }) => {
        const data = await getCityNameByCoordinates(
          coords.latitude,
          coords.longitude
        );

        search(data.address.city);
      },
      () => {
        setLoading(false);
        setError(true);
      }
    );
  };

  useEffect(() => {
    search("London");
  }, []);

  if (loading) {
    return <Loader />;
  }

  if (error) {
    return (
      <div className="error__wrapper">
        <SearchControls search={search} searchByLocation={searchByLocation} />
        <Error />
      </div>
    );
  }

  return (
    <div className="main">
      <SearchControls search={search} searchByLocation={searchByLocation} />
      <Router basename={process.env.PUBLIC_URL}>
        <Switch>
          <Route path="/" exact component={Home} />
          <Route path="/daily" exact component={Daily} />
        </Switch>
        <Navbar />
      </Router>
    </div>
  );
});
