// packages/weather-app-react/src/components/daily/HourlyWeather.tsx
import { HourlyWeatherItem } from "./HourlyWeatherItem";

const diffBetweenHours = 5;

export const HourlyWeather = ({
  temp
}: {
  temp: { morn: number; day: number; eve: number; night: number };
}) => {
  const startHour = 8;
  return (
    <div className="daily__hourly-weather">
      {Object.values(temp).map((item, index) => (
        <HourlyWeatherItem
          temp={Number(item)}
          hour={startHour + diffBetweenHours * index}
          key={index}
        />
      ))}
    </div>
  );
};

// packages/weather-app/src/components/daily/HourlyWeather.vue
<template>
  <div class="daily__hourly-weather">
    <HourlyWeatherItem
      v-for="(item, index) in Object.values(temp)"
      :key="index"
      :temp="Number(item)"
      :hour="startHour + diffBetweenHours * index"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import HourlyWeatherItem from "@/components/daily/HourlyWeatherItem.vue";
import type { Temperature } from "@/types";
export default defineComponent({
  components: {
    HourlyWeatherItem
  },
  props: {
    temp: {
      type: Object as () => Partial<Temperature>,
      required: true
    }
  },
  setup() {
    const startHour = 8;
    const diffBetweenHours = 5;

    return { startHour, diffBetweenHours };
  }
});
</script>

<style lang="scss" scoped>
.daily__hourly-weather {
  width: 100%;
  display: grid;
  grid-template-columns: 1fr 1fr;
  margin: 10px 0;
  margin-bottom: 15px;
}
</style>
