// packages/react/src/components/SearchControls/SearchControls.tsx
import { ReactComponent as SearchIcon } from "../../assets/icons/defaultSearch.svg";
import { ReactComponent as LocationSearchIcon } from "../../assets/icons/locationSearch.svg";
import { ChangeEvent, useState } from "react";

export const SearchControls = ({
  search,
  searchByLocation,
}: {
  search: (city: string) => Promise<void>;
  searchByLocation: () => Promise<void>;
}) => {
  const [query, setQuery] = useState("");

  const handleQueryUpdate = (e: ChangeEvent<HTMLInputElement>) => {
    setQuery(e.target.value);
  };

  const handleSearch = (e: React.FormEvent<EventTarget>) => {
    e.preventDefault();
    if (!query.trim().length) {
      return;
    }
    return search(query);
  };

  return (
    <form className="search" onSubmit={handleSearch}>
      <label htmlFor="search" className="sr-only">
        Search
      </label>
      <input
        id="search"
        type="search"
        role="search"
        placeholder="Search city"
        className="search__input"
        value={query}
        onChange={handleQueryUpdate}
      />
      <button className="search__btn search__btn--default" type="submit">
        <span className="sr-only">search</span>
        <SearchIcon />
      </button>
      <button
        className="search__btn search__btn--location"
        onClick={() => searchByLocation()}
      >
        <span className="sr-only">search by location</span>
        <LocationSearchIcon />
      </button>
    </form>
  );
};

// packages/vue/src/components/SearchControls.vue
<template>
  <form class="search" @submit="search">
    <label htmlFor="search" class="sr-only">Search</label>
    <input
      id="search"
      type="search"
      role="search"
      placeholder="Search city"
      class="search__input"
      v-model="query"
    />
    <button class="search__btn search__btn--default" type="submit">
      <span class="sr-only">search</span>
      <img src="@/assets/icons/defaultSearch.svg" alt="search" />
    </button>
    <button
      class="search__btn search__btn--location"
      @click="$emit('search-by-location')"
    >
      <span class="sr-only">search by location</span>
      <img src="@/assets/icons/locationSearch.svg" alt="location-search" />
    </button>
  </form>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
export default defineComponent({
  name: "SearchControls",
  setup(prp, ctx) {
    const query = ref("");

    function search(e: Event) {
      e.preventDefault();
      ctx.emit("search", query.value);
    }

    return { query, search };
  }
});
</script>

<style lang="scss" scoped>
.search {
  position: relative;
  top: 0;
  left: 0;
  text-align: center;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 20px 0;

  &__input {
    background: transparent;
    padding: 10px;
    font-size: 1rem;
    border: 0 none;
    border-bottom: 2px solid #000;
    width: 60vw;
    max-width: 400px;
    outline: 0 none;
    margin-right: 20px;

    &:focus {
      box-shadow: 0 3px 3px -1px gray;
      transition: 0.3s;
    }
  }

  &__btn {
    cursor: pointer;
    padding: 8px;
    border: 0 none;
    font-weight: bold;
    font-size: 1.3em;
    background-color: transparent;
    display: flex;
    justify-content: center;
    align-items: center;

    &:focus {
      opacity: 0.5;
      transition: opacity 0.2s;
    }

    img {
      width: 27px;
      height: 27px;
    }
  }
}
</style>
